import 'bootstrap/dist/css/bootstrap.css';
import '@/styles/styles.scss'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import { Footer } from "@/components/layout/footer/footer";
import { AuthClient } from '@/components/layout/authClient/authClient';
import { Chat } from '@/components/layout/chat/chat';
import ToastProvider from '@/components/providers/toast';
import { Header } from '@/components/layout/header/header';


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="ru">
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <ToastProvider>
                    <AuthClient />
                    <Header />
                    <div className='wrapper'>
                        <main>
                            {children}
                        </main>
                        <Footer />
                    </div>
                    <Chat />
                </ToastProvider>
            </body>
        </html>
    );
}
